{
 "title": "GPU Capacity Dashboard",
 "tags": [
  "gpu",
  "kubevirt",
  "kubernetes"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "NEO GPU Capacity Plans", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Cluster GPU Capacity",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubevirt_gpu_total_cluster_capacity",
     "legendFormat": "{{gpu_type}}"
    }
   ]
  },
  {
   "title": "GPU Used per Node",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubevirt_gpu_reserved{node!=\"\"}",
     "legendFormat": "{{node}} - {{gpu_type}}"
    }
   ]
  },
  {
   "title": "GPU Capacity per Node",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubevirt_gpu_capacity{node!=\"\"}",
     "legendFormat": "{{node}} - {{gpu_type}}"
    }
   ]
  },
  {
   "title": "GPU Available per Node",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubevirt_gpu_free{node!=\"\"}",
     "legendFormat": "{{node}} - {{gpu_type}}"
    }
   ]
  },
  {
   "title": "Listed VMs",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kubevirt_gpu_instance{node!=\"\", instance!=\"\"}",
     "legendFormat": "{{node}} - {{gpu_type}} - {{instance}}"
    }
   ]
  }
 ]
}