apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: gpu-capacity-exporter
  labels:
    app: gpu-capacity-exporter
spec:
  selector:
    matchLabels:
      app: gpu-capacity-exporter
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
  namespaceSelector:
    matchNames:
      - gpu-capacity-exporter